name: myenv
channels:
  - pytorch
  - pyg
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.3.0=py39h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - biopython=1.81=py39h72bdee0_0
  - biotite=0.37.0=py39h0f8d45d_0
  - blas=1.0=mkl
  - blosc=1.21.4=h0f2a231_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-blosc2=2.9.2=hb4ffafa_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py39hdb19cb5_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - easydict=1.9=py_0
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.3=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h516909a_1000
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.7.1=py39h06a4308_1
  - matplotlib-base=3.7.1=py39h417a72b_1
  - mdtraj=1.9.7=py39h62423bb_4
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py39h32b9844_0
  - mpich=4.0.3=h846660c_100
  - msgpack-python=1.0.3=py39hd09550d_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=pyhd8ed1ab_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py39hc78ab66_1
  - numpy=1.24.3=py39hf6e8229_1
  - numpy-base=1.24.3=py39h060ed82_1
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openmm=8.0.0=py39h7d85326_1
  - openssl=1.1.1u=hd590300_0
  - packaging=22.0=py39h06a4308_0
  - pandas=1.5.3=py39h417a72b_0
  - pcre=8.45=h295c915_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.0.1=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.1.0=py39_torch_1.11.0_cu113
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pysocks=1.7.1=py39h06a4308_0
  - pytables=3.8.0=py39h43249b6_2
  - python=3.9.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch-cluster=1.6.0=py39_torch_1.11.0_cu113
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py39_torch_1.11.0_cu113
  - pytorch-sparse=0.6.15=py39_torch_1.11.0_cu113
  - pytz=2022.7=py39h06a4308_0
  - pyyaml=6.0=py39hb9d737c_5
  - qt-main=5.15.2=h8373d8f_8
  - qt-webengine=5.15.9=hbbf29b9_6
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - scikit-learn=1.2.2=py39h6a678d5_1
  - scipy=1.10.1=py39hf6e8229_1
  - seaborn=0.12.2=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h9fff704_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py39h5eee18b_0
  - tqdm=4.65.0=py39hb070fc8_0
  - typing_extensions=4.5.0=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h166bdaf_4
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==0.4.3
      - alembic==1.13.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - autopage==0.5.2
      - awscli==1.31.10
      - blobfile==2.0.2
      - botocore==1.33.10
      - certifi==2023.11.17
      - cfgv==3.4.0
      - click==8.1.3
      - cliff==4.4.0
      - cmaes==0.10.0
      - cmake==3.26.4
      - cmd2==2.4.3
      - colorama==0.4.4
      - colorlog==6.8.0
      - contextlib2==21.6.0
      - cython==0.29.36
      - deepspeed==0.5.9
      - deeptime==0.4.4
      - deprecated==1.2.14
      - distlib==0.3.8
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docutils==0.16
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - fair-esm==2.0.0
      - filelock==3.13.1
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gputil==1.4.0
      - greenlet==3.0.2
      - hjson==3.1.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-joblib-launcher==1.2.0
      - hydra-optuna-sweeper==1.2.0
      - identify==2.5.33
      - imageio==2.31.1
      - imgaug==0.2.6
      - importlib-metadata==7.0.0
      - iniconfig==2.0.0
      - jmespath==1.0.1
      - joblib==1.3.2
      - lazy-loader==0.3
      - lightning==2.1.2
      - lightning-utilities==0.8.0
      - lit==16.0.6
      - lmdb==1.4.1
      - lxml==4.9.3
      - mako==1.3.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - ninja==1.11.1.1
      - nodeenv==1.8.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - opencv-python-headless==4.8.0.74
      - openreview-py==1.32.3
      - optuna==2.10.1
      - pathtools==0.1.2
      - pbr==6.0.0
      - piq==0.7.0
      - platformdirs==4.1.0
      - pluggy==1.3.0
      - pre-commit==3.6.0
      - prettytable==3.9.0
      - protobuf==4.23.2
      - psutil==5.9.5
      - pyasn1==0.5.1
      - pycryptodome==3.19.0
      - pycryptodomex==3.18.0
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pylatexenc==2.10
      - pyperclip==1.8.2
      - pytest==7.4.3
      - python-dotenv==1.0.0
      - pytorch-lightning==1.9.4
      - pywavelets==1.4.1
      - rich==13.7.0
      - rootutils==1.0.7
      - rsa==4.7.2
      - s3transfer==0.8.2
      - scikit-image==0.21.0
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - setuptools==65.5.1
      - smmap==5.0.0
      - sqlalchemy==2.0.23
      - src==0.0.1
      - stevedore==5.1.0
      - sympy==1.12
      - tifffile==2023.7.10
      - tld==0.13
      - tmtools==0.0.2
      - tomli==2.0.1
      - torch==2.0.1
      - torchmetrics==0.11.4
      - torchvision==0.15.2
      - triton==2.0.0
      - virtualenv==20.25.0
      - wandb==0.15.4
      - wcwidth==0.2.12
      - wrapt==1.16.0
      - yarl==1.9.2
